name: 'Run converter'
description: 'Runs converter on files specified'
inputs:
  file-name:
    description: 'Name of file to convert'
    required: true
  executable:
    description: 'Path to executable JS file'
    required: true
  aws-input-directory:
    description: 'AWS directory which contains input file'
    required: true
  aws-output-directory:
    description: 'AWS directory used to upload result file'
    required: true
  aws-bucket-name:
    description: 'name of AWS bucket to use'
    required: true
  conversion-type:
    description: 'Type of conversion'
    required: true
  post-message-enabled:
    description: 'Post message to commit once done'
    default: '1'
    required: false
  token:
    description: 'The GitHub authentication token'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'The full name of the target repository.'
    required: false
    default: ${{ github.repository }}
runs:
  using: 'node12'
  main: 'dist/index.js'
